import 'package:test/test.dart';
import 'package:path/path.dart' as p;
import 'package:claudart/commands/link.dart';
import 'package:claudart/codegen/artifact_state.dart';
import 'package:claudart/codegen/claudart_artifact.dart';
import 'package:claudart/codegen/dependency_config_codegen.dart';
import 'package:claudart/paths.dart';
import '../helpers/mocks.dart';

const _projectRoot = '/projects/my-app';
const _projectName = 'my-app';

Never _throwExit(int code) => throw _ExitException(code);

class _ExitException implements Exception {
  final int code;
  const _ExitException(this.code);
}

String get _workspace => workspaceFor(_projectName);

/// Links `_projectRoot` for real (through `runLink`), the same fixture used
/// by `link_test.dart` — the only reliable way to get a true "freshly
/// linked" baseline to assert staleness against.
Future<MemoryFileIO> _linked() async {
  final io = MemoryFileIO(files: {
    p.join(_projectRoot, 'pubspec.yaml'): 'name: $_projectName\n',
  });
  await runLink(
    [_projectName],
    io: io,
    projectRootOverride: _projectRoot,
    confirmFn: (_) => false,
    exitFn: _throwExit,
  );
  return io;
}

ArtifactState _state(ClaudartArtifact artifact, MemoryFileIO io) => stateOf(
      artifact,
      projectRoot: _projectRoot,
      workspace: _workspace,
      projectName: _projectName,
      io: io,
    );

void main() {
  group('ArtifactState.commandTemplates', () {
    test('missing when nothing was ever linked', () {
      final io = MemoryFileIO();
      expect(_state(ClaudartArtifact.commandTemplates, io), ArtifactState.missing);
    });

    test('stale when a command file was hand-edited', () async {
      final io = await _linked();
      final commandsDir = claudeCommandsDirFor(_workspace);
      final anyFile = io.files.keys.firstWhere((k) => k.startsWith('$commandsDir/'));
      io.write(anyFile, 'hand-edited, not the real template');
      expect(_state(ClaudartArtifact.commandTemplates, io), ArtifactState.stale);
    });

    test('fresh immediately after link', () async {
      final io = await _linked();
      expect(_state(ClaudartArtifact.commandTemplates, io), ArtifactState.fresh);
    });
  });

  group('ArtifactState.claudeMdTail', () {
    test('missing when CLAUDE.md does not exist', () {
      final io = MemoryFileIO();
      expect(_state(ClaudartArtifact.claudeMdTail, io), ArtifactState.missing);
    });

    test('missing when CLAUDE.md exists but has no generated marker', () {
      final io = MemoryFileIO(files: {
        claudeMdPathFor(_projectRoot): '# CLAUDE.md\n\nhand-written only.',
      });
      expect(_state(ClaudartArtifact.claudeMdTail, io), ArtifactState.missing);
    });

    test('stale when the generated tail was hand-edited', () async {
      final io = await _linked();
      final path = claudeMdPathFor(_projectRoot);
      final match = generatedMarker.firstMatch(io.read(path))!;
      io.write(path, '${io.read(path).substring(0, match.start)}## Generated by claudart link\nhand-edited.');
      expect(_state(ClaudartArtifact.claudeMdTail, io), ArtifactState.stale);
    });

    test('fresh immediately after link', () async {
      final io = await _linked();
      expect(_state(ClaudartArtifact.claudeMdTail, io), ArtifactState.fresh);
    });
  });

  group('ArtifactState.readmeRoadmap', () {
    test('notApplicable when there is no roadmap.json', () {
      final io = MemoryFileIO();
      expect(_state(ClaudartArtifact.readmeRoadmap, io), ArtifactState.notApplicable);
    });

    test('notApplicable when roadmap.json has no rows', () {
      final io = MemoryFileIO(files: {
        p.join(_projectRoot, 'roadmap.json'): '{"rows": []}',
      });
      expect(_state(ClaudartArtifact.readmeRoadmap, io), ArtifactState.notApplicable);
    });

    test('notApplicable when README.md has no roadmap marker', () {
      final io = MemoryFileIO(files: {
        p.join(_projectRoot, 'roadmap.json'):
            '{"rows": [{"phase": "1", "scope": "core", "status": "shipped"}]}',
        p.join(_projectRoot, 'README.md'): '# my-app\n\nNo roadmap marker here.',
      });
      expect(_state(ClaudartArtifact.readmeRoadmap, io), ArtifactState.notApplicable);
    });

    test('stale when the roadmap table was hand-edited', () {
      final io = MemoryFileIO(files: {
        p.join(_projectRoot, 'roadmap.json'):
            '{"rows": [{"phase": "1", "scope": "core", "status": "shipped"}]}',
        p.join(_projectRoot, 'README.md'):
            '# my-app\n\n<!-- claudart:link:roadmap -->\nhand-edited table\n---\n',
      });
      expect(_state(ClaudartArtifact.readmeRoadmap, io), ArtifactState.stale);
    });

    test('fresh when the roadmap table matches roadmap.json', () async {
      final io = MemoryFileIO(files: {
        p.join(_projectRoot, 'pubspec.yaml'): 'name: $_projectName\n',
        p.join(_projectRoot, 'roadmap.json'):
            '{"rows": [{"phase": "1", "scope": "core", "status": "shipped"}]}',
        p.join(_projectRoot, 'README.md'):
            '# my-app\n\n<!-- claudart:link:roadmap -->\nstale placeholder\n---\n',
      });
      // Let `runLink` perform the real splice, same as production — avoids
      // hand-constructing a spliced fixture and getting whitespace wrong.
      await runLink(
        [_projectName],
        io: io,
        projectRootOverride: _projectRoot,
        confirmFn: (_) => false,
        exitFn: _throwExit,
      );
      expect(_state(ClaudartArtifact.readmeRoadmap, io), ArtifactState.fresh);
    });
  });

  group('ArtifactState.dependencyConfig', () {
    test('notApplicable when there is no pubspec.yaml', () {
      final io = MemoryFileIO();
      expect(_state(ClaudartArtifact.dependencyConfig, io), ArtifactState.notApplicable);
    });

    test('missing when pubspec.yaml exists but nothing was generated yet', () {
      final io = MemoryFileIO(files: {
        p.join(_projectRoot, 'pubspec.yaml'): 'name: my_app\n',
      });
      expect(_state(ClaudartArtifact.dependencyConfig, io), ArtifactState.missing);
    });

    test('stale when the generated file was hand-edited', () async {
      final io = await _linked();
      io.write(
        p.join(_projectRoot, kDependencyConfigGeneratedRelativePath),
        'not what the codegen would render',
      );
      expect(_state(ClaudartArtifact.dependencyConfig, io), ArtifactState.stale);
    });

    test('fresh immediately after link', () async {
      final io = await _linked();
      expect(_state(ClaudartArtifact.dependencyConfig, io), ArtifactState.fresh);
    });
  });

  group('self-hosting: a freshly linked project has no drift', () {
    test('commandTemplates, claudeMdTail, and dependencyConfig are fresh', () async {
      final io = await _linked();
      expect(_state(ClaudartArtifact.commandTemplates, io), ArtifactState.fresh);
      expect(_state(ClaudartArtifact.claudeMdTail, io), ArtifactState.fresh);
      expect(_state(ClaudartArtifact.dependencyConfig, io), ArtifactState.fresh);
    });

    test('readmeRoadmap is notApplicable (this fixture never opts in)', () async {
      final io = await _linked();
      expect(_state(ClaudartArtifact.readmeRoadmap, io), ArtifactState.notApplicable);
    });
  });
}
