// claudart_artifact.dart — the 4 config-driven things `claudart link`
// regenerates, as one dispatchable enum.
//
// Each variant's actual render/write logic stays exactly where it already
// lived and worked (link.dart's own private functions) -- this enum is a
// dispatch point, not a rewrite of any of the 4. Deliberately NOT a
// generic `render()`/`sources()` interface: the 4 derivations have
// genuinely different shapes (commandTemplates writes N files from
// AgentFlow.values; claudeMdTail/readmeRoadmap splice a marker into one
// existing file; dependencyConfig writes one generated file from scratch)
// and forcing them into one artificial shape would have meant rewriting
// working, tested logic for the sake of surface uniformity. What step 5
// (the staleness state machine) actually needs is just `.values` to
// iterate over -- this gives it that, nothing more.

enum ClaudartArtifact {
  /// `.claude/commands/*.md` + `.cursor/commands` symlink — createProjectLinks.
  commandTemplates,

  /// CLAUDE.md's machine-owned tail section, below the
  /// `## Generated by claudart link` marker.
  claudeMdTail,

  /// README.md's Roadmap table, opt-in via roadmap.json + a marker.
  readmeRoadmap,

  /// `lib/generated/dependency_config.g.dart`, from this project's own
  /// pubspec.yaml.
  dependencyConfig,
}
