import 'package:test/test.dart';
import 'package:claudart/templates/claude_template.dart';

void main() {
  group('claudeTemplate', () {
    final base = claudeTemplate(
      workspacePath: '/workspace',
      projectName: 'my-app',
      genericFiles: ['dart.md', 'testing.md'],
    );

    test('starts with the marker heading claudart link splices on', () {
      expect(base, startsWith('## Generated by claudart link'));
    });

    test('includes project name', () {
      expect(base, contains('Project: my-app'));
    });

    test('lists generic knowledge files with absolute paths', () {
      expect(base, contains('/workspace/knowledge/generic/dart.md'));
      expect(base, contains('/workspace/knowledge/generic/testing.md'));
    });

    test('omits the Generic practices heading entirely when no files given', () {
      final t = claudeTemplate(
        workspacePath: '/workspace',
        projectName: 'my-app',
        genericFiles: [],
      );
      expect(t, isNot(contains('### Generic practices')));
      expect(t, contains('### Project context'));
    });

    test('includes project knowledge path', () {
      expect(base, contains('/workspace/knowledge/projects/my-app.md'));
    });

    test('includes session state paths', () {
      expect(base, contains('/workspace/handoff.md'));
      expect(base, contains('/workspace/skills.md'));
    });

    test('workflow protocol enforces verify before commit', () {
      expect(base, contains('Verify'));
      expect(base, contains('Never commit before testing'));
    });

    test('workflow protocol includes a plan step between verify and test', () {
      expect(base, contains('**Plan** — state what you intend to do before writing code'));
    });

    test('git rules forbid pushing to remote', () {
      expect(base, contains('Never push to remote'));
    });

    test('git rules require verifying identity before commit or push', () {
      expect(base, contains('Verify identity before any commit or push'));
      expect(base, contains('git -C <repo> config user.email'));
      expect(base, contains('gh auth status'));
    });

    test('no environment section when constraints absent', () {
      expect(base, isNot(contains('## Environment')));
    });

    test('includes environment section when sdk provided', () {
      final t = claudeTemplate(
        workspacePath: '/workspace',
        projectName: 'my-app',
        genericFiles: [],
        sdkConstraint: '^3.8.0',
      );
      expect(t, contains('## Environment'));
      expect(t, contains('Dart SDK: `^3.8.0`'));
    });

    test('includes flutter constraint when provided', () {
      final t = claudeTemplate(
        workspacePath: '/workspace',
        projectName: 'my-app',
        genericFiles: [],
        sdkConstraint: '^3.8.0',
        flutterConstraint: '3.32.5',
      );
      expect(t, contains('Flutter: `3.32.5`'));
    });

    test('includes analyzer instruction in environment section', () {
      final t = claudeTemplate(
        workspacePath: '/workspace',
        projectName: 'my-app',
        genericFiles: [],
        sdkConstraint: '^3.8.0',
      );
      expect(t, contains('Do not suggest APIs or syntax unavailable'));
    });
  });
}
