// portability_gap.dart — typed discrepancy ledger
//
// README_PORTABILITY.md's "Known portability gaps" table was hand-written
// prose the first time it was drafted — exactly the kind of bare,
// duplicated-across-files string this project's own paradigm forbids.
// Each row is now a PortabilityGapStatus-stamped enum variant instead, so
// the table (and any future consumer — a `claudart doctor` command, a
// test asserting the docs haven't drifted) reads from one typed source.
//
// Invariants:
//   for all g: g.whatsMissing.isNotEmpty
//   for all g: g.trackedIn.isNotEmpty
//   gaps close over time — when one ships, delete its variant and its
//   README_PORTABILITY.md row together, don't leave either behind.

/// Where a gap currently stands.
enum PortabilityGapStatus {
  /// A primitive/building block exists in code but isn't consulted yet by
  /// the real call site it's meant to guard.
  open,

  /// Explicitly deferred — no second concrete target exists to generalize
  /// against yet; building for a hypothetical one would be premature.
  tabled,

  /// Scoped and sequenced, but not started.
  planned;

  String get label => switch (this) {
        PortabilityGapStatus.open    => 'open',
        PortabilityGapStatus.tabled  => 'tabled',
        PortabilityGapStatus.planned => 'planned',
      };
}

enum PortabilityGap {
  /// `lib/commands/link.dart` creates `.claude/commands` and
  /// `.cursor/commands` only — zero Zed-editor-specific scaffolding.
  zedEditorIntegration(
    status: PortabilityGapStatus.tabled,
    whatsMissing:
        'lib/commands/link.dart creates .claude/commands and '
        '.cursor/commands only — zero Zed-editor-specific scaffolding, '
        "despite one real machine depending on Zed's own settings.json "
        'for its entire Bedrock auth chain',
    trackedIn:
        'tabled — no second real IDE target to generalize against yet; '
        'building for a hypothetical one would be premature abstraction',
  ),

  /// `ZedProfile` was checked and confirmed to be org identity
  /// (liitx/toyota), not IDE coupling — the real Zed-editor seam is the
  /// narrow `ZedHelper.zedLauncher`.
  zedupEnvWorkspaceResolution(
    status: PortabilityGapStatus.tabled,
    whatsMissing:
        'ZedProfile (zedup) is not actually IDE coupling — confirmed by '
        'reading it directly, it is liitx-vs-toyota org identity (branch '
        'types, PR templates, GitHub owners). The one real Zed-editor '
        'seam is narrow: ZedHelper.zedLauncher, which launches the zed '
        'binary. Do not conflate the two when scoping this',
    trackedIn: 'tabled alongside zedEditorIntegration',
  ),

  /// The Section 11 harness spec from the original machine-setup zip:
  /// idempotent, [OK]/[SKIP]/[FAIL]-logging checks across the whole
  /// fresh-machine setup surface. `claudart doctor` ships tools/git-
  /// identity/gh-auth/provider-env; clones/git-perf/Zed-settings-merge
  /// still need the original zip's exact spec re-verified before they're
  /// implemented for real.
  verificationHarness(
    status: PortabilityGapStatus.open,
    whatsMissing:
        'claudart doctor (lib/commands/doctor.dart) covers tools-on-PATH, '
        'git identity, gh auth, and provider env. Still missing: clones, '
        'git-performance, and Zed-settings-merge checks — guessing at '
        'those risks encoding a wrong assumption as a passing check, so '
        "they're deferred until the original zip's Section 11 spec is "
        're-verified',
    trackedIn: 'lib/commands/doctor.dart, test/commands/doctor_test.dart',
  ),

  /// This repo's own `CLAUDE.md` once hardcoded both its Paradigms pointer
  /// and its Knowledge base section to this machine's absolute paths. The
  /// Paradigms pointer now resolves dynamically (reads `dartrix`'s real
  /// install location from `.dart_tool/package_config.json`, falling back
  /// to a GitHub URL). The Knowledge base section's paths remain absolute
  /// — not a bug, that's `claudart link`'s own per-machine workspace
  /// layout by design (a fresh clone runs `claudart link` to regenerate
  /// them, same as the rest of CLAUDE.md's "Generated by claudart link"
  /// section), but a fresh clone that hasn't linked yet still sees stale
  /// paths in the meantime.
  hardcodedWorkspacePaths(
    status: PortabilityGapStatus.open,
    whatsMissing:
        "CLAUDE.md's Knowledge base section hardcodes this machine's "
        'absolute workspace paths until `claudart link` regenerates them '
        'for whichever machine actually runs it',
    trackedIn: 'CLAUDE.md',
  );

  const PortabilityGap({
    required this.status,
    required this.whatsMissing,
    required this.trackedIn,
  });

  /// Where this gap currently stands.
  final PortabilityGapStatus status;

  /// What's missing — the gap itself, in prose.
  final String whatsMissing;

  /// Where this gap is tracked / why it's at its current status.
  final String trackedIn;
}
