import 'dart:io';
import 'package:path/path.dart' as p;
import '../codegen/dependency_config_codegen.dart';
import '../dependency_config.dart';
import '../file_io.dart';
import '../git_utils.dart';
import '../md_io.dart' show confirmOrEof;
import '../paths.dart';
import '../pipeline/agent_flow.dart';
import '../registry.dart';
import '../templates/claude_template.dart';
import '../templates/command_template_marker.dart';
import '../templates/readme_template.dart';
import '../ui/render.dart' as render;

/// The heading `claudeTemplate`'s output always starts with — the splice
/// point between hand-maintained content (preserved) and machine-owned
/// content (regenerated).
final RegExp _generatedMarker =
    RegExp(r'^## Generated by claudart link.*$', multiLine: true);

/// The marker `readmeTemplate`'s output always starts with — the splice
/// point between the README's hand-curated `## Roadmap` heading (preserved,
/// keeps its TOC anchor) and the machine-owned table below it. Stops before
/// the next `---` section separator (not the next `## ` heading) — every
/// top-level README section is followed by a `---` rule before the next
/// heading, and stopping at `## ` instead would consume that separator,
/// visibly joining Roadmap to the following section. Unlike
/// `_generatedMarker`, this splice is opt-in: a README.md without this
/// marker is left untouched entirely, since (unlike CLAUDE.md) README.md is
/// not a claudart-owned file for every project.
///
/// `(?![\s\S])` is "end of input," not `\z` — Dart/JS regex has no `\z`
/// metacharacter (that's Perl/Python syntax); in ECMAScript-flavored regex
/// `\z` is silently a literal lowercase `z`. Using it here made the splice
/// stop at the first `z` in the roadmap content instead of the end of
/// input — worked by luck against claudart's own roadmap text (no `z`
/// appears in it), corrupted the first live run against a project whose
/// roadmap text contained "zedup," caught and fixed before landing.
final RegExp roadmapMarker = RegExp(
    r'^<!-- claudart:link:roadmap -->.*?(?=\n---|(?![\s\S]))',
    multiLine: true,
    dotAll: true);

const _sensitiveFlag = '--sensitive';
const _noSensitiveFlag = '--no-sensitive';

/// Registers the current project with claudart and creates the `.claude` symlink.
///
/// On first run: creates a per-project workspace, writes the registry entry,
/// and symlinks `<projectRoot>/.claude` → `<workspace>/.claude/`.
///
/// On re-run for an already-registered project: updates sensitivity mode and
/// recreates the symlink if missing.
///
/// Sensitivity mode is a protective setting, so it is never defaulted for
/// you: pass `--sensitive` or `--no-sensitive` to set it without a prompt,
/// otherwise the question is asked, and if there is nobody to answer (stdin
/// closed) the command stops before writing anything.
Future<void> runLink(
  List<String> args, {
  FileIO? io,
  String? projectRootOverride,
  bool Function(String question)? confirmFn,
  bool? Function(String question)? askFn,
  Never Function(int code)? exitFn,
}) async {
  final fileIO = io ?? const RealFileIO();
  // A caller-supplied confirm always answers; the default reports null at end
  // of input so a missing answer is never mistaken for "no". [askFn] lets a
  // test simulate "nobody to answer".
  final bool? Function(String question) ask =
      askFn ?? (confirmFn != null ? (String q) => confirmFn(q) : confirmOrEof);
  final exit_ = exitFn ?? exit;

  final unknownFlags = args.where((a) => a.startsWith('--') && a != _sensitiveFlag && a != _noSensitiveFlag);
  if (unknownFlags.isNotEmpty) {
    print('\n✗ Unknown option: ${unknownFlags.first}');
    print('  Usage: claudart link [project-name] [$_sensitiveFlag | $_noSensitiveFlag]\n');
    exit_(1);
  }
  final wantsSensitive = args.contains(_sensitiveFlag);
  final wantsNoSensitive = args.contains(_noSensitiveFlag);
  if (wantsSensitive && wantsNoSensitive) {
    print('\n✗ Pass only one of $_sensitiveFlag / $_noSensitiveFlag.\n');
    exit_(1);
  }
  final positional = args.where((a) => !a.startsWith('--')).toList();

  print(render.header('CLAUDART LINK'));

  // 1 — Detect project root.
  final projectRoot = resolveProjectRoot(override: projectRootOverride);
  if (projectRoot == null) {
    print('\n✗ Not inside a git repository. Cannot detect project root.\n');
    exit_(1);
  }

  // 2 — Resolve project name: arg > git remote > directory name.
  final projectName = positional.isNotEmpty
      ? positional.first
      : (projectRootOverride != null
          ? p.basename(projectRootOverride)
          : _detectProjectName(projectRoot));

  print('\n  Project : $projectName');
  print('  Root    : $projectRoot');

  // 3 — Load registry and check for existing entry.
  var registry = Registry.load(io: fileIO);
  final existing = registry.findByProjectRoot(projectRoot);

  if (existing != null && existing.name != projectName) {
    print('\n⚠  This project is already registered as "${existing.name}".');
    print('   Re-linking under the same name.');
  }

  final effectiveName = existing?.name ?? projectName;
  final workspace = workspaceFor(effectiveName);

  // 5 — Sensitivity mode.
  final currentSensitivity = existing?.sensitivityMode ?? false;
  bool? decided = wantsSensitive ? true : (wantsNoSensitive ? false : null);

  if (decided != null) {
    print('\n  Sensitivity mode: ${decided ? 'ON' : 'OFF'} '
        '(${wantsSensitive ? _sensitiveFlag : _noSensitiveFlag})');
  } else if (existing != null) {
    print('\n  Sensitivity mode is currently: '
        '${currentSensitivity ? 'ON' : 'OFF'}');
    final change = ask('Change sensitivity mode?');
    decided = change == null
        ? null
        : (change ? ask('Enable sensitivity mode?') : currentSensitivity);
  } else {
    decided = ask('Enable sensitivity mode?');
  }

  if (decided == null) {
    print('\n✗ No input available to answer the sensitivity-mode question, '
        'so nothing was changed.');
    print('  Re-run in a terminal, or pass $_sensitiveFlag or $_noSensitiveFlag.\n');
    exit_(1);
  }
  final sensitivityMode = decided;

  // 6 — Write or update registry entry.
  final today = DateTime.now().toIso8601String().split('T').first;
  final entry = RegistryEntry(
    name: effectiveName,
    projectRoot: projectRoot,
    workspacePath: workspace,
    createdAt: existing?.createdAt ?? today,
    lastSession: existing?.lastSession ?? today,
    sensitivityMode: sensitivityMode,
  );
  registry = registry.add(entry);
  registry.save(io: fileIO);

  // 7 — Workspace dirs, .claude/.cursor symlinks, command templates, .gitignore.
  final links = createProjectLinks(
    projectRoot: projectRoot,
    workspace: workspace,
    effectiveName: effectiveName,
    fileIO: fileIO,
  );

  // 9 — Regenerate CLAUDE.md's machine-owned tail section, preserving
  // everything hand-maintained above the `## Generated by claudart link`
  // marker. No SDK/Flutter constraints are known at link time — omitted,
  // same as any other caller of claudeTemplate that doesn't have them yet.
  // Generic knowledge files are read from disk, not assumed — a workspace
  // that never ran `claudart init` has no knowledge/generic/ at all, and
  // pointing at files that don't exist would be a dangling reference.
  final claudeMdPath = claudeMdPathFor(projectRoot);
  final existingClaudeMd =
      fileIO.fileExists(claudeMdPath) ? fileIO.read(claudeMdPath) : '';
  final genericFiles = fileIO
      .listFiles(genericKnowledgeDir, extension: '.md')
      .map(p.basename)
      .toList()
    ..sort();
  final generatedSection = claudeTemplate(
    workspacePath: workspace,
    projectName: effectiveName,
    genericFiles: genericFiles,
  );
  final markerMatch = _generatedMarker.firstMatch(existingClaudeMd);
  final String newClaudeMd;
  if (markerMatch != null) {
    newClaudeMd =
        existingClaudeMd.substring(0, markerMatch.start) + generatedSection;
  } else if (existingClaudeMd.isNotEmpty) {
    newClaudeMd = '${existingClaudeMd.trimRight()}\n\n---\n\n$generatedSection';
  } else {
    newClaudeMd = '# CLAUDE.md\n\n$generatedSection';
  }
  fileIO.write(claudeMdPath, newClaudeMd);

  // 10 — Regenerate README.md's Roadmap table, if the project opted in with
  // both a git-committed `roadmap.json` at its project root and the
  // `<!-- claudart:link:roadmap -->` marker in its README.md. roadmap.json,
  // not workspace.json: workspace.json lives outside every project's repo
  // (under ~/.claudart/), so it can never be a source a fresh clone or CI
  // could verify against. Unlike CLAUDE.md, most linked projects' README.md
  // is not claudart-owned — a missing marker or missing rows means "not
  // opted in," not "needs the section appended."
  final roadmapJsonPath = p.join(projectRoot, 'roadmap.json');
  final roadmapConfig = fileIO.fileExists(roadmapJsonPath)
      ? parseRoadmapConfig(fileIO.read(roadmapJsonPath))
      : null;
  if (roadmapConfig != null && roadmapConfig.rows.isNotEmpty) {
    final readmePath = p.join(projectRoot, 'README.md');
    final existingReadme =
        fileIO.fileExists(readmePath) ? fileIO.read(readmePath) : '';
    final readmeMarkerMatch = roadmapMarker.firstMatch(existingReadme);
    if (readmeMarkerMatch != null) {
      final generatedRoadmap = readmeTemplate(
        roadmapRows: roadmapConfig.rows,
        summaryText: roadmapConfig.summaryText ?? "What's coming",
        footerLine: roadmapConfig.footerLine,
      );
      final newReadme = existingReadme.replaceRange(
        readmeMarkerMatch.start,
        readmeMarkerMatch.end,
        generatedRoadmap,
      );
      fileIO.write(readmePath, newReadme);
    }
  }

  // 11 — Regenerate the dependency-config const from this project's own
  // pubspec.yaml, every time link runs — so "what's configured" and "what
  // the generated file says" never drift. Mirrors zedup's UserConfigCodegen
  // (manifest -> generated .g.dart const), the first use of the same
  // pattern in claudart. Rendered through the injected FileIO, not
  // DependencyConfigCodegen's own real-file writer -- every other write in
  // this function goes through fileIO so tests stay filesystem-free, and
  // this one is no different.
  final pubspecPath = p.join(projectRoot, 'pubspec.yaml');
  if (fileIO.fileExists(pubspecPath)) {
    const codegen = DependencyConfigCodegen();
    fileIO.write(
      p.join(projectRoot, kDependencyConfigGeneratedRelativePath),
      codegen.render(usesDartrix: detectsDartrixDependency(fileIO.read(pubspecPath))),
    );
  }

  print('\n✓ Registered: $effectiveName');
  print('  Workspace : $workspace');
  if (links.symlinkSkipped) {
    print(
        '  Commands  : .claude/commands/ (source directory, no symlink needed)');
  } else {
    print('  Symlink   : ${links.symlinkPath} → ${links.symlinkTarget}');
  }
  print('  Cursor    : ${links.cursorCmdsLink} → ${links.workspaceCmdsDir}');
  if (sensitivityMode) print('  Sensitivity mode: ON');
  print('\nRun `claudart setup` to begin a session.\n');
}

/// Result of [createProjectLinks] — the paths its caller reports to the user.
typedef ProjectLinks = ({
  String symlinkPath,
  String symlinkTarget,
  bool symlinkSkipped,
  String workspaceCmdsDir,
  String cursorCmdsLink,
});

/// Creates the workspace's `.claude/commands` dir, the `<projectRoot>/.claude`
/// symlink (or syncs a real directory if one already exists there), writes
/// every agent command template, symlinks `.cursor/commands`, and adds both
/// to `.gitignore` when it created the `.claude` symlink. Shared by `runLink` (existing project) and `runAdd` (new
/// project) — same mechanism, no duplicated logic. Does not touch CLAUDE.md;
/// callers that want the tail-regeneration step (`runLink`'s step 9) do that
/// separately, since a caller like `runAdd` writes CLAUDE.md from scratch
/// instead and must not have this function clobber it.
ProjectLinks createProjectLinks({
  required String projectRoot,
  required String workspace,
  required String effectiveName,
  required FileIO fileIO,
}) {
  fileIO.createDir(workspace);
  fileIO.createDir(p.join(workspace, IdeIntegration.claudeCode.dirName, 'commands'));

  final symlinkPath = p.join(projectRoot, IdeIntegration.claudeCode.dirName);
  final symlinkTarget = p.join(workspace, IdeIntegration.claudeCode.dirName);

  if (fileIO.linkExists(symlinkPath)) {
    print('\n⚠  Removing existing ${IdeIntegration.claudeCode.dirName} symlink.');
    fileIO.deleteLink(symlinkPath);
  }

  final symlinkSkipped = fileIO.dirExists(symlinkPath);
  if (symlinkSkipped) {
    print('\n⚠  ${IdeIntegration.claudeCode.dirName}/ is a real directory — symlink skipped.');
    print('  Slash commands in ${IdeIntegration.claudeCode.dirName}/commands/ are already available.');
  } else {
    fileIO.createLink(symlinkPath, symlinkTarget);
  }

  // Write all agent command templates to the workspace .claude/commands/.
  // Driven by AgentFlow.values — adding a new flow with hasCommandFile=true
  // automatically installs its template; no manual update required.
  final workspaceCmdsDir = p.join(workspace, IdeIntegration.claudeCode.dirName, 'commands');
  for (final flow in AgentFlow.values.where((f) => f.hasCommandFile)) {
    // Remove any un-suffixed legacy file first so pickers don't show duplicates.
    final legacy = p.join(workspaceCmdsDir, flow.legacyFileName);
    if (fileIO.fileExists(legacy)) fileIO.delete(legacy);
    fileIO.write(
      p.join(workspaceCmdsDir, flow.fileName(effectiveName)),
      flow.commandTemplate(workspace, effectiveName),
    );
  }

  // When .claude/ could not be symlinked (a real directory already existed
  // there), <projectRoot>/.claude/commands/ is a separate directory from
  // workspaceCmdsDir and would otherwise never receive template updates,
  // silently drifting stale. Sync it too. Its legacy (un-suffixed) filename is
  // kept rather than deleted — content is synced to the same template instead —
  // since a real directory may hold files the owner does not want removed.
  if (symlinkSkipped) {
    final realCmdsDir = p.join(projectRoot, IdeIntegration.claudeCode.dirName, 'commands');
    fileIO.createDir(realCmdsDir);
    for (final flow in AgentFlow.values.where((f) => f.hasCommandFile)) {
      final template = flow.commandTemplate(workspace, effectiveName);
      _writeCommandFile(
          fileIO, p.join(realCmdsDir, flow.legacyFileName), template);
      _writeCommandFile(
          fileIO, p.join(realCmdsDir, flow.fileName(effectiveName)), template);
    }
  }

  // Create .cursor/commands symlink for Cursor IDE slash command integration.
  // Cursor reads slash commands from .cursor/commands/ — same markdown format.
  final cursorDir = p.join(projectRoot, IdeIntegration.cursor.dirName);
  final cursorCmdsLink = p.join(cursorDir, 'commands');
  fileIO.createDir(cursorDir);
  if (fileIO.linkExists(cursorCmdsLink)) fileIO.deleteLink(cursorCmdsLink);
  if (!fileIO.dirExists(cursorCmdsLink)) {
    fileIO.createLink(cursorCmdsLink, workspaceCmdsDir);
  }

  // Auto-add .claude and .cursor/ to .gitignore, but only when claudart
  // actually created the .claude symlink. When .claude/ is a real directory
  // (symlinkSkipped) it holds the user's own tracked files, and git-ignoring
  // it would silently hide anything new written there.
  if (!symlinkSkipped) {
    _ensureGitignore(projectRoot, fileIO);
  }

  // If the project ships a tracked .githooks/ dir (this repo's own
  // pre-push paradigm gate, for one), point git at it. .git/hooks/ is
  // never committed — a fresh clone has nothing there until this runs,
  // which is exactly the gap that let a prior pre-push protection exist
  // on only one machine. A no-op for projects without that convention.
  _ensureHooksPath(projectRoot, fileIO);

  return (
    symlinkPath: symlinkPath,
    symlinkTarget: symlinkTarget,
    symlinkSkipped: symlinkSkipped,
    workspaceCmdsDir: workspaceCmdsDir,
    cursorCmdsLink: cursorCmdsLink,
  );
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/// True when [lines] already ignores [entry], accepting `.claude`, `.claude/`
/// and `/.claude` as the same thing so a re-link never appends a duplicate.
bool _gitignoreHas(List<String> lines, String entry) {
  final bare = entry.replaceAll('/', '');
  return lines.any((l) => l.trim().replaceAll('/', '') == bare);
}

void _ensureGitignore(String projectRoot, FileIO fileIO) {
  final path = p.join(projectRoot, '.gitignore');
  var current = fileIO.read(path);
  final lines = current.split('\n');

  final missing = <String>[
    if (!_gitignoreHas(lines, IdeIntegration.claudeCode.dirName)) IdeIntegration.claudeCode.dirName,
    if (!_gitignoreHas(lines, '${IdeIntegration.cursor.dirName}/')) '${IdeIntegration.cursor.dirName}/',
  ];

  if (missing.isEmpty) return;

  current = current.isEmpty
      ? '${missing.join('\n')}\n'
      : '${current.trimRight()}\n${missing.join('\n')}\n';

  fileIO.write(path, current);
  print('  .gitignore: added ${missing.join(', ')}');
}

const _githooksDirName = '.githooks';

void _ensureHooksPath(String projectRoot, FileIO fileIO) {
  if (!fileIO.dirExists(p.join(projectRoot, _githooksDirName))) return;
  final previous = readGitConfig(GitConfigKey.hooksPath, workingDirectory: projectRoot) ?? '';
  if (previous == _githooksDirName) return;

  writeGitConfig(GitConfigKey.hooksPath, _githooksDirName, workingDirectory: projectRoot);
  // A non-empty previous value means something else (husky, lefthook, a
  // hand-set path) already owned this — say what was replaced instead of
  // silently clobbering it, so a project with its own hooks convention
  // notices immediately rather than finding out when those hooks stop
  // firing.
  print(previous.isEmpty
      ? '  git hooks: ${GitConfigKey.hooksPath.gitKey} → $_githooksDirName'
      : '  git hooks: ${GitConfigKey.hooksPath.gitKey} $previous → $_githooksDirName (replaced)');
}

/// Writes a command template file, but never over a file that already
/// exists and was not written by claudart — that would clobber a user's
/// own command of the same name.
void _writeCommandFile(FileIO fileIO, String path, String content) {
  if (fileIO.fileExists(path) &&
      !isClaudartGeneratedCommand(fileIO.read(path))) {
    print('  ⚠  Skipped $path — not a claudart-generated file.');
    return;
  }
  fileIO.write(path, content);
}

String _detectProjectName(String projectRoot) {
  try {
    final result = Process.runSync(
      'git',
      ['remote', 'get-url', 'origin'],
      workingDirectory: projectRoot,
    );
    if (result.exitCode == 0) {
      final url = (result.stdout as String).trim();
      if (url.isNotEmpty) {
        final name = url.split('/').last.replaceAll('.git', '').trim();
        if (name.isNotEmpty) return name;
      }
    }
  } on Exception catch (_) {}
  return p.basename(projectRoot);
}
